"""Generate the Windows to Olson timezone mapping module windows_to_olson.py."""

# Source - https://stackoverflow.com/a/16157049
# Posted by unutbu, modified by community. See post 'Timeline' for change history
# Retrieved 2026-07-16, License - CC BY-SA 3.0

# Source - https://stackoverflow.com/a/10469748
# Posted by mzjn, modified by community. See post 'Timeline' for change history
# Retrieved 2026-07-16, License - CC BY-SA 3.0

import json
import urllib.request as req
from pathlib import Path

import lxml.etree as et

# Get the XML data from the CLDR on GitHub and save to a file.
# Unfortunately, the CLDR does not have a latest or stable tag
# that points to the stable version.
# Use the `main` branch, which is the development branch.
url = "https://raw.githubusercontent.com/unicode-org/cldr/refs/heads/main/common/supplemental/windowsZones.xml"
with req.urlopen(url) as response:  # noqa: S310
    xml_content = response.read()

# Parse the XML file and extract the timezone mapping.
result = {}
tree = et.fromstring(xml_content)
for zone in tree.xpath("//mapZone"):
    attrib = zone.attrib
    if attrib["territory"] == "001":
        result[attrib["other"]] = attrib["type"]

HERE = Path(__file__).parent
DEST = HERE / "src" / "icalendar" / "timezone"
file = "windows_to_olson.py"
filepath = Path(DEST, file)
print(f"Writing {filepath}")  # noqa: T201
with Path.open(filepath, "w") as f:
    f.write("""\"\"\"
This module contains mappings from Windows timezone identifiers to
Olson timezone identifiers.

This file is automatically generated by generate_windows_to_olson_mapping.py.
Do not edit manually.

The data is taken from the Unicode Consortium [0].

The proposal and rationale for this mapping is also available at the
Unicode Consortium [1].

[0] https://raw.githubusercontent.com/unicode-org/cldr/refs/heads/main/common/supplemental/windowsZones.xml
[1] https://cldr.unicode.org/development/development-process/design-proposals/extended-windows-olson-zid-mapping

\"\"\"

""")
    f.write("WINDOWS_TO_OLSON = ")
    f.write(json.dumps(dict(result), indent=4, sort_keys=True))
    f.write("\n")
