"""Generate the Windows to Olson timezone mapping module windows_to_olson.py."""

# Source - https://stackoverflow.com/a/16157049
# Posted by unutbu, modified by community. See post 'Timeline' for change history
# Retrieved 2026-07-16, License - CC BY-SA 3.0

# Source - https://stackoverflow.com/a/10469748
# Posted by mzjn, modified by community. See post 'Timeline' for change history
# Retrieved 2026-07-16, License - CC BY-SA 3.0

import json
import urllib.request as req
import xml.etree.ElementTree as ET
from pathlib import Path

CLDR_PATH = "common/supplemental/windowsZones.xml"
commits_url = (
    f"https://api.github.com/repos/unicode-org/cldr/commits?path={CLDR_PATH}&per_page=1"
)
with req.urlopen(commits_url) as response:  # noqa: S310
    version = json.load(response)[0]["sha"]

# Fetch the XML from the commit recorded in the generated module. Using the
# commit instead of `main` ensures that the data and version cannot diverge if
# CLDR changes between the two requests.
url = f"https://raw.githubusercontent.com/unicode-org/cldr/{version}/{CLDR_PATH}"
with req.urlopen(url) as response:  # noqa: S310
    xml_content = response.read()

# Parse the XML file and extract the timezone mapping.
result = {}
tree = ET.fromstring(xml_content)  # noqa: S314
for zone in tree.findall(".//mapZone"):
    attrib = zone.attrib
    if attrib["territory"] == "001":
        result[attrib["other"]] = attrib["type"]

HERE = Path(__file__).parent
DEST = HERE / "src" / "icalendar" / "timezone"
file = "windows_to_olson.py"
filepath = Path(DEST, file)
print(f"Writing {filepath}")  # noqa: T201
with Path.open(filepath, "w") as f:
    f.write(f'''"""
This module contains mappings from Windows timezone identifiers to
Olson timezone identifiers.

This file is automatically generated by generate_windows_to_olson_mapping.py.
Do not edit manually.

The data is taken from the Unicode Consortium [0] at commit
``{version}``.

The proposal and rationale for this mapping is also available at the
Unicode Consortium [1].

[0] https://github.com/unicode-org/cldr/blob/{version}/{CLDR_PATH}
[1] https://cldr.unicode.org/development/development-process/design-proposals/extended-windows-olson-zid-mapping

"""

version = "{version}"

''')
    f.write("WINDOWS_TO_OLSON = ")
    f.write(json.dumps(dict(result), indent=4, sort_keys=True))
    f.write("\n")
