# to run for a specific environment, use ``tox -e ENVNAME``
[tox]
envlist = py310,py311,py312,py313,py314,pypy3,docs,nopytz
# Note: the 'docs' env creates a 'build' directory which may interfere in strange ways
# with the other environments.  You might see this when you run the tests in parallel.
# See https://github.com/collective/icalendar/pull/359#issuecomment-1214150269

[testenv]
description = test environment
runner = uv-venv-lock-runner
dependency_groups = dev
commands =
    coverage run --branch --source=src/icalendar --omit=*/tests/hypothesis/* --omit=*/tests/fuzzed/* --module pytest []
    coverage report
    coverage html
    coverage xml

[testenv:nopytz]
# install with dependencies
usedevelop = False
# use lowest version
basepython = python3.10
deps =
    pytest
    coverage
    hypothesis
commands =
    coverage run --branch --source=src/icalendar --omit=*/tests/hypothesis/* --omit=*/tests/fuzzed/* --module pytest []
    coverage report
    coverage html
    coverage xml

[testenv:docs]
dependency_groups = docs
allowlist_externals =
    make
commands =
    make docs-all

[testenv:ruff]
# use tox -e ruff to format the code base
deps =
skip_install = True
dependency_groups = formatting
commands =
    ruff format
    ruff check --fix
