# .github/workflows/rtd-pr-preview.yml
# Usage: https://github.com/readthedocs/actions/blob/v1/preview/README.md
name: readthedocs/actions
on:
  pull_request_target:
    types:
      - opened
    # Execute this action only on PRs that touch
    # documentation files.
    paths:
      - "docs/**"
      - "src/icalendar/**/*.py"
      - .github/workflows/documentation.yml
      - .github/workflows/rtd-pr-preview.yml
      - .readthedocs.yml
      - .vale.ini
      - CHANGES.rst
      - Makefile
      - pyproject.toml
      - "!src/icalendar/fuzzing"
      - "!src/icalendar/tests"
      - "!src/icalendar/timezone"

permissions:
  pull-requests: write

jobs:
  documentation-links:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "icalendar"
