name: zizmor static analysis

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install zizmor
        run: pip install zizmor==1.29.0
      - name: Run zizmor
        run: zizmor --format sarif .github/workflows/ > zizmor-results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938  # v4.37.9
        with:
          sarif_file: zizmor-results.sarif
