name: zizmor static analysis

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install zizmor
        run: pip install zizmor
      - name: Run zizmor
        run: zizmor --format sarif .github/workflows/ > zizmor-results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@ea14db8afdef5d462e69d78c4ca45002d4522418 # v4.37.4
        with:
          sarif_file: zizmor-results.sarif